# Example config.yaml for liturgical_display
# Package handles its own caching internally
output_image: /home/pi/liturgical_display/today.png
vcom: -1.18
shutdown_after_display: false
log_file: /home/pi/liturgical_display/logs/display.log 