name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make test scripts executable
        run: |
          chmod +x run_tests.sh
          chmod +x tests/test_systemd_static.sh
          chmod +x tests/test_systemd_timer_in_docker.sh
          chmod +x tests/test_integration.sh || true

      - name: Run all tests
        run: |
          sudo ./run_tests.sh 